# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('spirit', models.CharField(blank=True, choices=[('A', 'Alternative'), ('B', 'Hipster'), ('C', 'Chic'), ('D', 'Local'), ('E', 'Elegant'), ('F', 'Tacky')], max_length=120)),
                ('location', models.CharField(max_length=250)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, default=0, max_digits=9)),
            ],
        ),
    ]
