# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_auto_20160623_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='venue',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=10, default=0, max_digits=14),
        ),
    ]
