# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_auto_20160623_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/venue_images/'),
        ),
    ]
