# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-21 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20160608_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(blank=True, to='profiles.Job'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='places',
            field=models.ManyToManyField(blank=True, to='profiles.Place'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='schools',
            field=models.ManyToManyField(blank=True, to='profiles.School'),
        ),
    ]
