# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField()),
                ('num_people', models.IntegerField()),
                ('event_type', models.CharField(choices=[('B', 'BAR'), ('H', 'HOUSE PARTY'), ('C', 'CLUBBING'), ('O', 'OTHER')], max_length=1)),
                ('location', models.CharField(max_length=250, unique=True)),
                ('max_invit', models.IntegerField()),
                ('num_girl', models.IntegerField(blank=True)),
                ('num_boy', models.IntegerField(blank=True)),
                ('sp_score_req', models.DecimalField(decimal_places=8, default=0.0, max_digits=16)),
                ('byo', models.BooleanField(default=False)),
                ('cash', models.IntegerField(blank=True, default=0)),
                ('other', models.CharField(blank=True, max_length=300, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('guests', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
