# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_picture'),
        ('events', '0005_auto_20160606_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ManyToManyField(blank=True, to='venues.Venue'),
        ),
    ]
