# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_type',
        ),
        migrations.AlterField(
            model_name='event',
            name='sp_score_req',
            field=models.DecimalField(blank=True, decimal_places=8, default=0.0, max_digits=16),
        ),
    ]
