# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20160629_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, choices=[('B', 'BAR'), ('H', 'HOUSE PARTY'), ('C', 'CLUBBING'), ('O', 'OTHER')], max_length=1),
        ),
    ]
