# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-29 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.DateTimeField(null=True),
        ),
    ]
