# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_event_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spirit_picture',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/spirit_pics/'),
        ),
    ]
